### ISSUE TITLE
fletcore error :P

### ISSUE THREAD

**Issue by Liamm114** [openandroidinstaller-dev/openandroidinstaller#699]
I keep getting an:

Traceback (most recent call last):
  File "openandroidinstaller.py", line 39, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "views\__init__.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "views\addon_view.py", line 31, in <module>
ModuleNotFoundError: No module named 'flet_core'

error.

**Comment by tsterbak** [comment]
Hi, thanks for reporting this issue.
Which OS and Installer version are you using?

**Comment by tsterbak** [comment]
Hm I see :/

**Comment by tsterbak** [comment]
Seems to affect at least both versions of the ubuntu/debian executable. Probably also Windows. The flatpak is fine though.

**Comment by tsterbak** [comment]
@Liamm114 I pushed a fix now that resolves the issue. Please give it a try and let me know if it works for you now :)

**Comment by JAOT** [comment]
Hi! Error still persists:
![Image](https://github.com/user-attachments/assets/3e3ae815-80a3-4e42-8509-f848c41fc51d)
OS: Win 11
Using latest fix version from 5 days ago.

**Comment by tsterbak** [comment]
Hey thanks for reporting again :)
I should really get a Windows setup for debugging again...
I'll look into it

**Comment by JAOT** [comment]
> Hey thanks for reporting again :) I should really get a Windows setup for debugging again... I'll look into it

No problem. Also, my phone reports as unsupported:
Xiaomi 13T, codename "aristotle".

**Comment by Liamm114** [comment]
Sorry for not responding, I forgot to mention that I was leaving for a vacation same day.

**Comment by VirusBurst** [comment]
Same issue w/ my Windows 10 LTSC 2021 (21H2) but beta 0.5.4 w/o fixes works fine

**Comment by theroch** [comment]
Same issue under W10 22H2.
"openandroidinstaller-v0.5.4-beta-windows-latest.zip" worked for me.
Notice:
"openandroidinstaller-v0.5.4-beta-windows-latest.zip" is three times bigger than the newer ones, so I think there are some dependencies missing inside.

**Comment by avichalk** [comment]
Was having a similar issue installing Flatpak v0.5.4-beta.1 on Fedora Atomic. The GUI does not launch, errors out with the below trace. 

`  WARNING: The script uvicorn is installed in '/var/data/python/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script dotenv is installed in '/var/data/python/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script watchfiles is installed in '/var/data/python/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  
File "/app/lib/python3.11/site-packages/openandroidinstaller/openandroidinstaller.py", line 333, in <module>
    startup()
  File "/app/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/openandroidinstaller/openandroidinstaller.py", line 326, in startup
    ft.app(
  File "/app/lib/python3.11/site-packages/flet/app.py", line 64, in app
    return asyncio.run(
           ^^^^^^^^^^^^
  File "/app/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/flet/app.py", line 156, in app_async
    else await __run_web_server(
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/flet/app.py", line 285, in __run_web_server
    from flet_web.fastapi.serve_fastapi_web_app import serve_fastapi_web_app
ModuleNotFoundError: No module named 'flet_web'
`

On adding '/var/data/python/bin' to PATH, I get a different error.

`ERROR:    [Errno 98] error while attempting to bind on address ('::', 8000, 0, 0): address already in use`

**Comment by tsterbak** [comment]
This should be resolved with the latest release #695
